#!/bin/bash

I=0

#"brew update && brew upgrade" \
for UPDATE in \
	"cargo install-update -a" \
	"rustup update" \
	"yarn upgrade-interactive --latest" \
	"sudo apt update && sudo apt upgrade" \
; do
	task add +runnable +update recur:14d "due:today + $I days" wait:due "host:freddie-ThinkPad-X220" $UPDATE

	((I= $I + 1))
done;

task add +update recur:7d "due:monday" wait:due $UPDATE
